# Generated by Django 5.2.6 on 2025-10-26 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('actividad', 'Nueva Actividad'), ('calificacion', 'Calificación Recibida'), ('monedas', 'Monedas Recibidas'), ('subasta_nueva', 'Nueva Subasta'), ('subasta_ganada', 'Subasta Ganada'), ('anuncio', 'Anuncio'), ('general', 'General')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('activity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_id', models.PositiveIntegerField(blank=True, null=True)),
                ('auction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8fe80f_idx'), models.Index(fields=['-creado'], name='notificatio_creado_b02e49_idx')],
            },
        ),
    ]
