# Generated by Django 5.2.6 on 2025-11-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('actividad', 'Nueva Actividad'), ('calificacion', 'Calificación Recibida'), ('monedas', 'Monedas Recibidas'), ('subasta_nueva', 'Nueva Subasta'), ('subasta_ganada', 'Subasta Ganada'), ('anuncio', 'Anuncio'), ('general', 'General')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('activity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_id', models.PositiveIntegerField(blank=True, null=True)),
                ('auction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
