# Generated by Django 5.2.6 on 2025-11-09 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8fe80f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-creado'], name='notificatio_creado_b02e49_idx'),
        ),
    ]
