# Generated by Django 5.2.6 on 2025-11-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('actividad', 'Nueva Actividad'), ('calificacion', 'Calificación Recibida'), ('monedas', 'Monedas Recibidas'), ('subasta_nueva', 'Nueva Subasta'), ('subasta_ganada', 'Subasta Ganada'), ('anuncio', 'Anuncio'), ('general', 'General'), ('email_verificado', 'Email Verificado'), ('password_changed', 'Contraseña Cambiada'), ('password_reset', 'Contraseña Restablecida'), ('login_failed', 'Intento de Login Fallido'), ('account_security', 'Alerta de Seguridad')], max_length=20),
        ),
    ]
