# Generated by Django 5.2.6 on 2025-09-29 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'estudiante'}, related_name='clases_estudiante', to=settings.AUTH_USER_MODEL),
        ),
    ]
