# Generated by Django 5.2.6 on 2025-11-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_generado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo_expira_en', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_clases', to='classrooms.classroom')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
