# Generated by Django 5.2.6 on 2025-11-09 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='grupos_estudiante', to=settings.AUTH_USER_MODEL),
        ),
    ]
