# Generated by Django 5.2.6 on 2025-09-29 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(limit_choices_to={'role': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(blank=True, limit_choices_to={'role': 'estudiante'}, related_name='classrooms_estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['-creado'],
            },
        ),
    ]
