# Generated by Django 5.2.6 on 2025-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('on_time', 'Tarea a tiempo'), ('late', 'Tarea tardía'), ('auction', 'Subasta'), ('reward', 'Recompensa'), ('other', 'Otro')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billetera Educoin',
                'verbose_name_plural': 'Billeteras Educoin',
            },
        ),
    ]
