# Generated by Django 5.2.6 on 2025-09-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educoinwallet',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educointransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='coins.educoinwallet'),
        ),
        migrations.AlterUniqueTogether(
            name='educoinwallet',
            unique_together={('student', 'group')},
        ),
    ]
