# Generated by Django 5.2.6 on 2025-11-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='periodo',
        ),
        migrations.AddField(
            model_name='auction',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='groups.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró esta puja (estudiante o docente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
