# Generated by Django 5.2.6 on 2025-11-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
