# Generated by Django 5.2.6 on 2025-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='valor_minimo',
            field=models.PositiveIntegerField(default=1, help_text='Valor mínimo para pujar en esta subasta'),
        ),
    ]
