# Generated by Django 5.2.6 on 2025-09-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_alter_classroom_options_remove_classroom_estudiantes_and_more'),
        ('groups', '0002_alter_group_options_alter_group_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('parcial', 'Parcial'), ('proyecto', 'Proyecto'), ('quiz', 'Quiz'), ('exposicion', 'Exposición')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_educoins', models.PositiveIntegerField(default=0)),
                ('valor_notas', models.PositiveIntegerField(default=0)),
                ('fecha_entrega', models.DateField()),
                ('habilitada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='classrooms.classroom')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group')),
            ],
        ),
    ]
