# Generated by Django 5.2.6 on 2025-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='valor_notas',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
