# Generated by Django 5.2.6 on 2025-10-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
