# Generated by Django 5.2.6 on 2025-11-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
    ]
